# @package _global_
vector_quantizer:
  _target_: emg2qwerty.vector_quantizer.ResidualVectorQuantizer
  parent_block_id: 1  # Insert vector_quantizer after the first encoder block
  n_vq: 4  # Residual VQ with 4 codebooks
  codebook_size: 1024   # 10 bits per timestep per codebook; 40 bits per timestep overall
  codebook_init: kmeans  # Init codebook weights via k-means
  kmeans_max_iters: 300
  kmeans_rtol: 1e-6
  ema_update: True  # Update codebook weights via EMA
  ema_decay: 0.9
  ema_expire_code_threshold: 2.0
