# @package _global_
vector_quantizer:
  _target_: emg2qwerty.vector_quantizer.VectorQuantizer
  parent_block_id: 1
  codebook_size: 256
  kmeans_init: True
  kmeans_max_iters: 300
  kmeans_rtol: 1e-6
